Adam_optimizer:
  initial_lr: 0.1
  lr_scheduler: cosine
  max_grad_norm: 1.0
  weight_decay: 0.0001
Dataset:
  num_locations: 2418
  num_users: 7800
  sequence_length: 20
  topic_num: 400
Embedding:
  base_dim: 16
Encoder:
  encoder_type: trans
Model:
  at_type: attn
  batch_size: 256
  epoch: 100
  seed: 1234
  test_epoch: 100
